---
version: "2.1"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1026
      - PGID=1000
      - TZ=America/Denver
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /volume1/books/Calibre:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
